@startuml
'https://plantuml.com/class-diagram
'scale 2
class Slime
class Hero extends Character {
    + hp: Int
    - name: String

    attack(slime: Slime)
}

class SuperHero extends Hero implements Attackable, Runnable

abstract class Character {
    {abstract} +attack(slime: Slime)
}

interface Attackable {
    {abstract} +attack()
}

interface Runnable {
    {abstract} +run()
}

@enduml